coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
ignore:
  - "python/*"      # pyblas wrappers
  - "src/python/*"  # py03 interface 
  - "src/julia/*"   # ClarabelRs wrapper 
